### ISSUE TITLE
Install on Debian.

### ISSUE THREAD

**Issue by Bolly** [lliurex/llx-guest#1]
Debian installation.

Hi, thanks for this great tool.
Is there any way to install on Debian?

**Comment by juanma1980** [comment]
I apologize for getting back to you late.
Theorically it could be possible on a Debian Testing as LliureX is a mix from Ubuntu/Neon distros (lliurex 21 ~ Ubuntu focal) but you know that things could get bad when mixing packages from different distros. 
Personally I would not recommend this.

**Comment by Bolly** [comment]
Now I apologise. For the time it has taken me to respond.
Thank you.
